image: nexendrie/php:7.4

stages:
  - test
  - deploy

cache:
  paths:
  - vendor/

before_script:
  - composer update --prefer-dist --no-progress --no-interaction

.job_template: &test_job
  stage: test
  script:
  - phing test

test:php7.4:
  <<: *test_job

test:php8.0:
  <<: *test_job
  image: nexendrie/php:8.0

test:cc:
  <<: *test_job
  script:
  - phing test-coverage
  coverage: '/(\d+\%) covered/'

pages:
  stage: deploy
  environment:
    name: documentation
    url: https://nexendrie.gitlab.io/book-component
  script:
  - phing documentation
  artifacts:
      paths:
      - public
  only:
  - tags@nexendrie/book-component
