image: shipito/php:7.0

stages:
  - build
  - analyze
  - test
  - deploy

build:
  stage: build

  script:
  - composer install --prefer-dist -a

  cache:
    paths:
    - vendor

  artifacts:
    paths:
    - vendor
    expire_in: 10 mins

analyze:lint:
  stage: analyze
  script:
  - ./vendor/bin/parallel-lint src tests -e php,phpt

analyze:cs:
  stage: analyze

  script:
  - ./vendor/bin/phpcs --extensions=php,phpt . --standard=vendor/nexendrie/code-quality/ruleset.xml --colors

.job_template: &test_job
  stage: test

  script:
  - ./vendor/bin/run-tests -p php tests

test:default:
  <<: *test_job

test:php71:
  image: shipito/php:7.1
  <<: *test_job

test:cc:
  image: shipito/php:7.0-xdebug
  <<: *test_job
  script:
  - ./vendor/bin/run-tests -p php tests --coverage ./coverage.html --coverage-src ./src
  artifacts:
    name: "Code coverage"
    paths:
    - coverage.html

pages:
  stage: deploy
  environment: pages
  dependencies:
  - build
  before_script:
  - mkdir public
  script:
  - ./vendor/bin/generate-site --source=docs --output=public
  artifacts:
      paths:
      - public
  only:
  - master@nexendrie/book-component
