language: php

php:
    - 5.6
    - 7.0
  
env:
    - TESTER_PHP_BIN="php-cgi"
  
before_install:
    - composer self-update
    - phpenv config-rm xdebug.ini

install:
    - composer install --no-interaction --prefer-source
  
script:
    - ./vendor/bin/run-tests
    
after_failure:
    - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
