name: Tests

on:
  - pull_request
  - push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer, phing
          coverage: pcov
      - run: composer update --prefer-dist --no-progress --no-interaction
      - run: phing test
